export { ARC402WalletClient, ARC402Wallet, type ContextBinding } from "./wallet";
export { ARC402WalletClient as ARC402OperatorClient, ARC402Wallet as ARC402Operator } from "./wallet";
export { ContractInteractionClient, type IntentPayload, type ContractCallAttestation, type ContractCallResult } from "./contractinteraction";
export { PolicyClient, PolicyObject, PolicyValidator } from "./policy";
export { TrustClient, TrustPrimitive } from "./trust";
export { IntentAttestationClient, IntentAttestation } from "./intent";
export { SettlementClient, MultiAgentSettlement } from "./settlement";
export { AgentRegistryClient, type AgentRegistrationInput } from "./agent";
export { ServiceAgreementClient } from "./agreement";
export { DisputeArbitrationClient } from "./dispute-arbitration";
export { ReputationOracleClient } from "./reputation";
export { SponsorshipAttestationClient } from "./sponsorship";
export { CapabilityRegistryClient } from "./capability";
export { GovernanceClient } from "./governance";
export { signNegotiationMessage, createSignedProposal, createSignedCounter, createSignedAccept, createSignedReject, createNegotiationProposal, createNegotiationCounter, createNegotiationAccept, createNegotiationReject, parseNegotiationMessage } from "./negotiation";
export { NegotiationGuard } from "./negotiation-guard";
export { SessionManager } from "./session-manager";
export { ChannelClient } from "./channel";
export { AgreementTreeClient, type AgreementTree, type PaymentSplit, type PaymentDistribution, type CreateAgreementResult } from "./multiparty";
export { WatchtowerClient } from "./watchtower";
export type { WatchtowerMetadata, WatchtowerStatus } from "./watchtower";
export { DeliverableClient, DeliverableType, hashDeliverable, hashDeliverableFile, uploadToIPFS, encryptDeliverable, decryptDeliverable, uploadEncryptedIPFS } from "./deliverable";
export type { DeliverableManifest, DeliverableManifestEntry, IPFSUploadOptions, IPFSUploadResult, EncryptedDeliverable } from "./deliverable";
export type { NegotiationVerificationResult, NegotiationVerificationError, SignedNegotiationMessage } from "./types";
export type { ChannelState, Channel, ChannelStatus, OpenChannelParams } from "./types";
export * from "./contracts";
export * from "./types";
export { buildMetadata, validateMetadata, encodeMetadata, decodeMetadata, uploadMetadata, AGENT_METADATA_SCHEMA } from "./metadata";
export type { AgentMetadata, AgentMetadataModel, AgentMetadataTraining, AgentMetadataPricing, AgentMetadataSla, AgentMetadataContact, AgentMetadataSecurity } from "./metadata";
export { ColdStartClient } from "./coldstart";
export { ComputeAgreementClient } from "./compute";
export type { ComputeSession, ComputeUsageReport } from "./compute";
export { MigrationClient } from "./migration";
export { ArenaClient, ARENA_ADDRESSES } from "./arena";
export type { ArenaRound, ArenaSquad, ArenaBriefing, ArenaArtifact, ArenaStatus, ArenaNewsletter, ArenaArtifactParams } from "./arena";
export { resolveEndpoint, notifyEndpoint, notifyHire, notifyHandshake, notifyHireAccepted, notifyDelivery, notifyDeliveryAccepted, notifyDispute, notifyMessage, DEFAULT_REGISTRY_ADDRESS } from "./endpoint";
export type { EndpointNotifyResult } from "./endpoint";
export { DeliveryClient, DEFAULT_DAEMON_URL } from "./delivery";
export type { DeliveryFile, DeliveryManifest, DeliveryClientOptions } from "./delivery";

// Base Mainnet contract addresses
export const COMPUTE_AGREEMENT_ADDRESS = "0xf898A8A2cF9900A588B174d9f96349BBA95e57F3";
export const SUBSCRIPTION_AGREEMENT_ADDRESS = "0x809c1D997Eab3531Eb2d01FCD5120Ac786D850D6";
export const ARC402_REGISTRY_V2_ADDRESS = "0xcc0D8731ccCf6CFfF4e66F6d68cA86330Ea8B622";
export const ARC402_REGISTRY_V3_ADDRESS = "0x6EafeD4FA103D2De04DDee157e35A8e8df91B6A6";
